-- c:\Users\Ali\Desktop\Love u\supabase_upgrade.sql

-- 1. Таблица для профилей пользователей (имена, аватарки)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE,
  avatar_url text,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Таблица для постов в галерее
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  image_url text NOT NULL,
  caption text,
  created_at timestamptz DEFAULT now()
);

-- Добавляем колонку caption, если таблица уже создана
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS caption text;

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can view posts." ON public.posts FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert their own posts." ON public.posts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own posts." ON public.posts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 3. Таблица для лайков
CREATE TABLE IF NOT EXISTS public.likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  CONSTRAINT likes_unique UNIQUE (post_id, user_id) -- Один юзер - один лайк на пост
);

ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can view likes." ON public.likes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert their own likes." ON public.likes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own likes." ON public.likes FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 4. Таблица для сообщений в чате
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content text, -- для текстовых сообщений
  audio_url text, -- для голосовых
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can view and send messages." ON public.chat_messages FOR ALL TO authenticated USING (true);

-- 5. Создаем Storage Buckets для галереи и голосовых сообщений
-- (Это нужно сделать вручную в интерфейсе Supabase, если не создадутся автоматически)
INSERT INTO storage.buckets (id, name, public)
VALUES ('gallery', 'gallery', true), ('voice_messages', 'voice_messages', true)
ON CONFLICT (id) DO NOTHING;

-- Политики для Storage
CREATE POLICY "Authenticated users can upload to gallery" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'gallery');
CREATE POLICY "Anyone can view gallery images" ON storage.objects FOR SELECT USING (bucket_id = 'gallery');
CREATE POLICY "Authenticated users can upload voice messages" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'voice_messages');
CREATE POLICY "Anyone can listen to voice messages" ON storage.objects FOR SELECT USING (bucket_id = 'voice_messages');
